package domains.peopleSkills;

public enum SkillLevel {

    BEGINNER, /*INICIANTE*/
    INTERMEDIATE, /*INTERMEDIÁRIO*/
    ADVANCED, /*AVANÇADO*/
    EXPERT, /*ESPECIALISTA*/
    MASTER, /*MESTRE*/
    NOVICE, /*NOVATO*/
    PROFICIENT, /*PROFICIENTE*/
    ENTRY_LEVEL, /*NÍVEL DE ENTRADA*/
    EXPERIENCED, /*EXPERIENTE*/
    ADVANCED_BEGINNER /*INICIANTE AVANÇADO*/
}
